services:
  - type: web
    name: hamkar-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FILE_UPLOAD_PATH
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: MONGODB_URI
        sync: false # Set this manually in Render dashboard
